version: '2.3'
services:
  web:
    build: .
    runtime: nvidia
    command: python3 api.py
    ports: 
      - 7000:7000

  web2:
    build: .
    runtime: nvidia
    command: python3 api.py
    ports: 
      - 7001:7000
    
